version: "3.3"

services:
  nginx:
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: rodrigo/nginx_appbuzz:v1
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - nwbuzz
    depends_on:
      - appbuzz

  postgre:
    build: 
      dockerfile: ./docker/pgbuzz.dockerfile
      context: .
    image: postgre/appbuzz:v1
    ports:
      - "5432"
    networks:
      - nwbuzz
    volumes:
      - pgdata:/var/lib/postgresql/data/

  appbuzz:
    build: 
      dockerfile: ./docker/appbuzz.dockerfile
      context: .
    image: rodrigo/app:v1
    container_name: app_bot_carros
    ports:
      - "8000"
    networks:
      - nwbuzz
    depends_on:
      - postgre

  redis:
    image: 'redis'
    networks:
      - nwbuzz

networks:
  nwbuzz:
    driver: bridge

volumes:
  pgdata: