# Generated by Django 3.2.6 on 2022-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=15)),
                ('km', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=1500)),
                ('found_in', models.CharField(max_length=1500)),
                ('provider_name', models.CharField(max_length=150)),
                ('provider_url', models.CharField(max_length=1000)),
                ('update', models.DateField(auto_now=True)),
                ('photo', models.CharField(max_length=2500)),
                ('disclosed', models.DateField()),
                ('owners', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['price'],
            },
        ),
    ]
