# Generated by Django 3.2.6 on 2022-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='nome do carro')),
                ('price', models.CharField(max_length=15, verbose_name='preço')),
                ('km', models.CharField(max_length=100, verbose_name='kilometragem')),
                ('year', models.CharField(max_length=15, verbose_name='ano')),
                ('source', models.CharField(max_length=1500, verbose_name='link do anuncio')),
                ('found_in', models.CharField(max_length=1500, verbose_name='url onde foi encontrado')),
                ('provider_name', models.CharField(max_length=150, verbose_name='Empresa anunciante')),
                ('update', models.DateField(auto_now=True, verbose_name='atualizado em')),
                ('photo', models.CharField(max_length=2500, verbose_name='foto')),
                ('disclosed', models.DateField(verbose_name='Anunciado em')),
                ('owners', models.CharField(max_length=50, verbose_name='quantidade de donos')),
                ('visible', models.IntegerField(verbose_name='visivel')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['price'],
            },
        ),
    ]
