# Generated by Django 3.2.6 on 2022-05-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='disclosed',
            field=models.DateField(verbose_name='Anunciado em'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='found_in',
            field=models.CharField(max_length=1500, verbose_name='url onde foi encontrado'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='km',
            field=models.CharField(max_length=100, verbose_name='kilometragem'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=300, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='owners',
            field=models.CharField(max_length=50, verbose_name='quantidade de donos'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='photo',
            field=models.CharField(max_length=2500, verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=15, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='provider_name',
            field=models.CharField(max_length=150, verbose_name='Empresa anunciante'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='provider_url',
            field=models.CharField(max_length=1000, verbose_name='site da empresa anunciante'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='source',
            field=models.CharField(max_length=1500, verbose_name='link do anuncio'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='update',
            field=models.DateField(auto_now=True, verbose_name='atualizado em'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.CharField(max_length=15, verbose_name='ano'),
        ),
    ]
